### ISSUE TITLE
Error when trying to use Falcon-7B

### ISSUE THREAD

**Issue by ktaletsk** [chenhunghan/ialacol#32]
I get the same error when Falcon 7B pod starts. Looks like the model file was deleted: https://huggingface.co/TheBloke/WizardLM-Uncensored-Falcon-7B-GGML/commit/7343df6eea4cfef162077380d075b49fdc9364ee

### Deploy
```bash
helm install falcon-7b ialacol/ialacol -f examples/values/falcon-7b.yaml
```

Pod logs:
```
INFO:     Started server process [1]
INFO:     Waiting for application startup.
Error downloading model: 404 Client Error. (Request ID: Root=1-64d11005-11d0783d650eb9652ee63f84)

Entry Not Found for url: https://huggingface.co/TheBloke/WizardLM-Uncensored-Falcon-7B-GGML/resolve/main/wizard-falcon-7b.ggmlv3.q4_1.bin.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
```

**Comment by chenhunghan** [comment]
Thank you, they might have changed the file name, newest seems to be https://huggingface.co/TheBloke/WizardLM-Uncensored-Falcon-7B-GGML/blob/main/wizardlm-7b-uncensored.ggccv1.q4_0.bin

**Comment by ktaletsk** [comment]
@chenhunghan yes, this new model at least can be loaded when the pod starts, but I hit the issue with when I try to make any request:

```
INFO:     Started server process [1]
INFO:     Waiting for application startup.
Downloading (…)ored.ggccv1.q4_0.bin: 100%|██████████| 4.06G/4.06G [01:24<00:00, 48.0MB/s]
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
error loading model: unknown (magic, version) combination: 67676363, 0000000a; is this really a GGML file?
llama_load_model_from_file: failed to load model
INFO:     <ip>:56448 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 227, in app
    solved_result = await solve_dependencies(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/dependencies/utils.py", line 622, in solve_dependencies
    solved = await call(**sub_values)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/get_llm.py", line 44, in get_llm
    return AutoModelForCausalLM.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ctransformers/hub.py", line 168, in from_pretrained
    return LLM(
           ^^^^
  File "/usr/local/lib/python3.11/site-packages/ctransformers/llm.py", line 214, in __init__
    raise RuntimeError(
RuntimeError: Failed to create LLM 'llama' from './models/wizardlm-7b-uncensored.ggccv1.q4_0.bin'.
```

Helm values:
```
deployment:
  env:
    DEFAULT_MODEL_HG_REPO_ID: TheBloke/WizardLM-Uncensored-Falcon-7B-GGML
    DEFAULT_MODEL_FILE: wizardlm-7b-uncensored.ggccv1.q4_0.bin
```

**Comment by chenhunghan** [comment]
Thank you for testing, unfortunately it's because the model file name doesn't contain `falcon` therefore the naive (silly) detection of model type failed, we can add a way to manually specify the model type via env.

**Comment by ktaletsk** [comment]
Hi @chenhunghan 👋
Looks like the fix was incomplete, since the `MODE_TYPE` was not added to the `deployment.yaml`
